### ISSUE TITLE
Crash win creating a new world.

### ISSUE THREAD

**Issue by NJM1564** [SilentChaos512/Silent-Gear#698] opened 2024-10-06 12:43 UTC
Looks like a conflict with gobber.
[crash-2024-10-06_08.37.36-client.txt](https://github.com/user-attachments/files/17269383/crash-2024-10-06_08.37.36-client.txt)

**Comment by SilentChaos512** [comment] 2024-10-06 13:00
Closing this as a duplicate of #691

**Closed as completed by SilentChaos512** 2024-10-06 13:00 UTC
Labels: bug, duplicate, 1.21
