### ISSUE TITLE
i am having issues with silent gear and silent gems causing modloader crash on startup i even just did your mods thats it with forge and same issue

### ISSUE THREAD

**Issue by pantingPUMA99** [SilentChaos512/Silent-Gear#495] opened 2022-03-01 17:30 UTC
## Versions

- **Silent Gear**: 2.9.0
- **Silent's Gems**: 4.2.0
- **Silent Lib**: 6.1.0
- **Forge**: 39.1.1
- **Modpack**: custom
- **Optifine Installed**: yes. vers: preview_OptiFine_1.18.1_HD_U_H5_pre6

## Expected Behavior
to at least load the game to the menu at the least

(Description here)

## Actual Behavior
gives me error. an unexpected issue occured and the game has crashed. were sorry for the inconvienence. this crash may be caused by invalid java runtime configuration. check any custom config settings.

## Links/Images
(https://pastebin.com/FJSRTs9G) debug log
https://pastebin.com/bQg0ejpu latest log.

## Steps to Reproduce the Problem

1.download latest forge.
2.download latest java
3.download silent gear and gems along with library. hit play.

**Comment by pantingPUMA99** [comment] 2022-03-01 17:31
mind you i recreated this without optifine as well

**Comment by pantingPUMA99** [comment] 2022-03-01 17:32
also i have this recreated with 366 mod on my modpack. so its a persistant issue

**Comment by ScoutTheSaneless** [comment] 2022-03-01 20:10
can confirm

**Comment by SilentChaos512** [comment] 2022-03-02 12:03
Duplicate of #494. Please check other issues before reporting.

**Closed as completed by SilentChaos512** 2022-03-02 12:03 UTC
Labels: bug
