### ISSUE TITLE
[Bug] Crafting Station loses crafting inventory on close (RealBench)

### ISSUE THREAD

**Issue by Dragnier** [SilentChaos512/Silent-Gear#4] opened 2018-08-28 22:06 UTC
### Versions

Minecraft Version: 1.12.2
Silent Gear Version: 0.1.1-38
Silent Lib Version: 3.0.1-145

### Expected behavior

- Closing the crafting station window should keep the items in the crafting grid, send the items back to the player inventory, or drop the items in the world.

### Actual behaviour

- The items in the crafting grid are deleted when the window is closed.

### Steps to reproduce the problem

1. Place crafting station
2. Put items in crafting grid
3. Close crafting station window
4. Poof!

**Comment by SilentChaos512** [comment] 2018-08-28 23:50
Seems to be functioning normally for me. Items are either returned to the player or dropped on the ground if there is no room. Perhaps a mod interaction? Or is there a something specific that triggers this?

**Comment by Dragnier** [comment] 2018-08-29 08:16
Specifically? It was a stone pickaxe head from your mod and two stone rods from Inspirations before I realized they were the wrong rods.

**Comment by SilentChaos512** [comment] 2018-08-29 17:25
Still seems normal with just Silent Gear and a couple other mods. Could you give me a full list of mods you are using, please?

**Comment by Dragnier** [comment] 2018-08-30 13:45
Here's an export of the pack from the Curse/Twitch App. It's just some stuff I put together.

[Thaumcraft++-1.0.zip](https://github.com/SilentChaos512/Silent-Gear/files/2336383/Thaumcraft%2B%2B-1.0.zip)

**Comment by SilentChaos512** [comment] 2018-09-02 20:10
Caused by RealBench. I'll see if there's any way to fix this.

**Comment by SilentChaos512** [comment] 2018-11-17 16:31
Fixed in 0.3.1

**Closed as completed by SilentChaos512** 2018-11-17 16:31 UTC
Labels: bug
