### ISSUE TITLE
Durability is VISUALLY stuck as if a tool were still at 95%

### ISSUE THREAD

**Issue by iShockGIT** [SilentChaos512/Silent-Gear#459] opened 2021-12-15 15:37 UTC
## Versions

- **Silent Gear**: 1.18-2.8.0
- **Silent's Gems**: N/A
- **Silent Lib**: 1.18-6.0.0
- **Forge**: 1.18.1-39.0.5
- **Modpack**: N/A
- **Optifine Installed**: Yes (But I get the same result without Optifine)

## Expected Behavior
I expect the durability bar to go down with the actual durability. But it's staying at where it is.

(Description here)

## Actual Behavior
The durability bar is stuck at where it is. (Yes, this only happens with Silent Gear tools, it works fine with regular vanilla tools.

(Description here)

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1. Get a stone tool and turn it into a Silent Gear tool
2. Then go into survival and then use it until it gets to like 50/max
3. Then you'll notice the durability bar is stuck as if it were at like 95% durability
![2021-12-15_09 34 49](https://user-images.githubusercontent.com/18996042/146216583-b7eb38c0-c5d0-453a-af85-abda7873f794.png)

**Comment by drakosoldier298** [comment] 2021-12-15 16:31
THis is a duplicate of #451

**Closed as completed** 2021-12-17 20:45 UTC
Labels: bug, duplicate
