### ISSUE TITLE
cant see info on sgear material even with keybinds

### ISSUE THREAD

**Issue by Gayanfalor** [SilentChaos512/Silent-Gear#319] opened 2021-02-01 12:29 UTC
## Versions
SilentGear-1.16.3-2.5.4+212

SilentGems-1.16.3-3.7.9+112
SilentLib-1.16.3-4.9.1+64
- **Forge**: 36.0.13
- **Modpack**: the final frontier 2
- **Optifine Installed**: No

## Expected Behavior
working as normal see the stats of each materials etc

## Actual Behavior
Nothing happen 

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by SilentChaos512** [comment] 2021-02-01 14:58
Likely duplicate of #314. Please update and try again.

If the issue persists, please reopen with more information, including a log file.

**Comment by Gayanfalor** [comment] 2021-02-01 16:34
dunno some other player on the pack says they can see it maybe key conflict block it ? i never blocked it before dunno why now it is

**Comment by SilentChaos512** [comment] 2021-02-01 17:05
It might be a keybind conflict, especially if the key was changed. It's supposed to just look for Ctrl key presses regardless of keybindings if it hasn't been changed.

**Comment by Gayanfalor** [comment] 2021-02-01 17:07
i have changed them for right alt and right ctrl and its not even wokring and they arent in conflict.By default on the pack they were unbinded

**Comment by SilentChaos512** [comment] 2021-02-01 17:09
The left keys are the default, not the right. Guess I should code the override to check for both of those.

**Comment by Gayanfalor** [comment] 2021-02-01 17:11
i rebinded key on the left ctsl and now i can see the material info  :o  
![image](https://user-images.githubusercontent.com/10771109/106492966-d7126880-64b8-11eb-990d-50c7f607474a.png)


its a bit like even if we change the binds the game still want it to be left ctrl?

**Closed as completed** 2021-02-22 02:47 UTC
Labels: bug
