### ISSUE TITLE
Nether ore generation needs to be configurable

### ISSUE THREAD

**Issue by Sinhika** [SilentChaos512/Silent-Gear#298] opened 2020-12-24 20:11 UTC
## What Should Be Added or Changed?

- To my surprise, Silent Gear generates ores in the nether. There is no hint of this in the configuration file. Please provide an option for, at the very least, turning off silent_gear ore generation like you do for Silent's Mechanisms ore generation.

## Why Should This Be Done?

- If one is building a modpack with other nether ore generation mods, the nether gets very crowded with different ores. Allowing users or modpack makers to customize what generates in their world is always desireable.

**Comment by SilentChaos512** [comment] 2020-12-24 20:15
Duplicate of #269. This was added in a recent update.

**Closed as completed by SilentChaos512** 2020-12-24 20:15 UTC
Labels: duplicate, enhancement
