### ISSUE TITLE
Server crashes on latest version do to recalculation issues.

### ISSUE THREAD

**Issue by choombdev** [SilentChaos512/Silent-Gear#465] opened 2021-12-20 11:38 UTC
## Versions

- **Silent Gear**: silent-gear-1.16.5-2.6.35.jar
- **Silent's Gems**: SilentGems-1.16.3-3.7.16.jar
- **Silent Lib**: silent-lib-1.16.5-4.10.0.jar
- **Forge**: forge-1.16.5-36.2.20
- **Modpack**: Odyssey 2
- **Optifine Installed**: No 

## Expected Behavior

Modded server to launch once updated to latest version.

## Actual Behavior

Server crashes instead.

## Links/Images

[- (Link)](https://paste.gg/p/anonymous/6b7c7f09031f400dbb5f16b7794e2674)

## Steps to Reproduce the Problem

1. Update to latest version of all mods.
2. Launch the server.

**Comment by SilentChaos512** [comment] 2021-12-20 12:29
Likely duplicate of #456. Aside from your stacktrace being much longer and containing Immersive Engineering code at any rate. But both mention the same MathHelper method not existing.

**Comment by choombdev** [comment] 2021-12-20 12:45
I was looking earlier at similar issues and I believe this could be that forge removed the method? Found similar threads on Forge's forums with the mods saying so, not exactly a mod developer, just thought this maybe could help

**Closed as completed** 2021-12-29 23:35 UTC
Labels: bug, duplicate
