### ISSUE TITLE
Crash (CME in PartManager)

### ISSUE THREAD

**Issue by eloe79** [SilentChaos512/Silent-Gear#104] opened 2020-04-02 18:24 UTC
https://github.com/Darkhax-Minecraft/Dark-Utilities/issues/202
https://github.com/sinkillerj/ProjectE/issues/1989

**Comment by SilentChaos512** [comment] 2020-04-02 20:09
The log file doesn't seem to match the crash report. If the crash is reproducible, could I get an updated log file please?

**Comment by eloe79** [comment] 2020-04-03 04:41
[crash-2020-04-01_19.21.35-client.txt](https://github.com/SilentChaos512/Silent-Gear/files/4425071/crash-2020-04-01_19.21.35-client.txt)
[2020-04-01-2.log](https://github.com/SilentChaos512/Silent-Gear/files/4425076/2020-04-01-2.log)
sorry for that, i hope this two are matching

**Comment by SilentChaos512** [comment] 2020-04-03 12:30
Thanks. Not sure what exactly the cause is, but I have an idea how to fix it. Unfortunately I can't test the fix since it never crashes like that for me. Uploading version 1.5.5, please get back to me on whether or not this fixes the issue.

**Comment by Vaelzan** [comment] 2020-04-03 12:52
To add to this, I've had players of our mod pack (Valhelsia 2) encounter a similar CME when Quark Oddities loads its magnet system. It's happening pretty frequently (had quite a few reports on our Discord in the last couple of days) so it might be an easy way to reproduce it for testing.

Example Crash Report: https://pastebin.com/Xntpsc49

**Comment by waddon1** [comment] 2020-04-03 13:07
I've also had a CME with Quark. https://pastebin.com/0YapTa7r I'll try again with the new version later to see if it has been fixed

**Comment by waddon1** [comment] 2020-04-03 18:53
Tried it again and it's still happening with version 1.5.5+80

**Comment by SilentChaos512** [comment] 2020-04-03 20:46
~~Most likely needs to be fixed by whatever the other mod is, the `harmonised.pmmo` at the top of the stacktrace.~~

Oops, wrong issue

**Comment by Vaelzan** [comment] 2020-04-05 18:43
None of the logs in this thread have Project MMO in them (the mod you're referring to with harmonised.pmmo), so I'm not sure what you're referring to there. Did you have a different log open when replying?

**Comment by SilentChaos512** [comment] 2020-04-05 18:53
Looks like I replied to the wrong issue there? Will verify when I get home.

**Comment by SilentChaos512** [comment] 2020-05-18 15:24
Can anyone confirm if this was fixed in 1.6.2 or higher?

**Comment by Vaelzan** [comment] 2020-05-19 20:02
I can't outright confirm it, but I've not seen this crash report in our support channel (Valhelsia) recently, so I suspect it may be fine now - I'm reasonably confident that somebody would have linked a crash report there if it was still happening, given the size of the pack / Discord.

**Comment by waddon1** [comment] 2020-05-19 21:15
I readded it to my modpack and it does appear to be fixed

**Comment by SilentChaos512** [comment] 2020-05-19 21:46
Much appreciated, I'll consider this closed.

**Closed as completed by SilentChaos512** 2020-05-19 21:46 UTC
Labels: bug, can't reproduce
