### ISSUE TITLE
[1.19.2] Bort ore does not generate

### ISSUE THREAD

**Issue by Draskh** [SilentChaos512/Silent-Gear#548] opened 2022-11-05 23:05 UTC
## Versions

- **Silent Gear**: 3.0.5
- **Silent's Gems**: 4.4.0
- **Silent Lib**: 7.0.3
- **Forge**: 43.1.43

## Expected Behavior
Bort Ore to be found in the overworld. I checked with Digital Miner, No Bort ore anywhere.

**Comment by SilentChaos512** [comment] 2022-11-06 14:20
Duplicate of #541

**Closed as completed by SilentChaos512** 2022-11-06 14:20 UTC
Labels: bug
