### ISSUE TITLE
Right click to wear sgear elytras causes crash game and corrupt world save 

### ISSUE THREAD

**Issue by jumpthe11** [SilentChaos512/Silent-Gear#435] opened 2021-10-06 08:17 UTC
## Versions

- **Silent Gear**: 2.6.31
- **Silent's Gems**: x.x.x 
- **Silent Lib**: 4.10.0
- **Forge**: 36.2.6
- **Modpack**: ATM6
- **Optifine Installed**: No

## Expected Behavior
**Right click** to wear the elytra

## Actual Behavior

Game freezes after equipped the elytra, then the game crashes

## Links/Images

[crash-2021-10-06_11.15.53-server.txt](https://github.com/SilentChaos512/Silent-Gear/files/7306369/crash-2021-10-06_11.15.53-server.txt)
https://youtu.be/kNSdWY6Dycg

## Steps to Reproduce the Problem

1. Craft custom made elytra
2. Right click the elytra
3.
4. Rage

**Comment by SilentChaos512** [comment] 2021-10-06 10:57
You have to provide a crash report. I can't tell you anything without one.

**Comment by jumpthe11** [comment] 2021-10-06 12:06
> 
> 
> You have to provide a crash report. I can't tell you anything without one.
[crash-2021-10-06_11.15.53-server.txt](https://github.com/SilentChaos512/Silent-Gear/files/7293535/crash-2021-10-06_11.15.53-server.txt)

**Comment by Sleet827** [comment] 2021-10-07 19:55
> > You have to provide a crash report. I can't tell you anything without one.
> > [crash-2021-10-06_11.15.53-server.txt](https://github.com/SilentChaos512/Silent-Gear/files/7293535/crash-2021-10-06_11.15.53-server.txt)

Try sgear alone (I mean outside the modpack), so we can truly know whether this is an SGear issue or some other mod is conflicting

**Comment by SilentChaos512** [comment] 2021-10-07 22:37
Duplicate of #432

**Comment by jumpthe11** [comment] 2021-10-08 10:04
> Try sgear alone (I mean outside the modpack), so we can truly know whether this is an SGear issue or some other mod is conflicting

Probably baubles mod causes. When I try wear the elytra game tries wear to *back slot* and crashres.

**Comment by SilentChaos512** [comment] 2021-10-08 11:15
Your crash report appears to be exactly the same as the issue I marked this as a duplicate of. It's something I will need to fix, according to the Curios dev. I'll work on it as soon as I get the chance.

**Closed as completed** 2021-10-09 11:33 UTC
Labels: bug, duplicate
