### ISSUE TITLE
Materials Disappearing on Restart

### ISSUE THREAD

**Issue by Rumaan3012** [SilentChaos512/Silent-Gear#487] opened 2022-01-23 18:31 UTC
## Versions

- **Silent Gear**: 2.8.6
- **Silent's Gems**: N/A
- **Silent Lib**: 6.0.0
- **Forge**: 39.0.43
- **Modpack**: ATM7 v0.2.34
- **Optifine Installed**: No

## Expected Behavior
On server restart items in the machine's inventory are still inside of the machines afterwards.

## Actual Behavior
When the server restarted a custom gem and a gold/Crimson Steel ingot disappeared from the Material Grader and Metal Alloyer respectively. I assumed I got unlucky with the gem in the Grader and it was changing inventories due to the hoppers when the server restarted, but then I noticed I had lost the only Crimson Steel ingot I had that had been left in the Metal Alloyer while it was in the "Work: Off" position.

## Links/Images
N/A

## Steps to Reproduce the Problem

1. Insert items into the SG machines
2. Restart server
3. Check to see if items are still inside of the machines

**Comment by Mecr0mage** [comment] 2022-02-07 02:34
this is happening to me on the ATM7 modpack server as well, if i dont take everything out of silent gear machines before reset they are all lost. regardless of working status or items in them, they are all voided upon reset.
silent-gear-1.16.5=2.6.30.jar

**Comment by InsipidSin** [comment] 2022-02-14 10:35
ATM v2.40, looks like silent still hasn't been able to address this issue. I genuinely hope they're focusing on bugs whenever possible before working on new content for the mod. Anyway, I've personally lost 4 SSS, and 6 stacks of the Tier 3 dust since i left the material grader running (and being fed by a hopper) while my groups server owner was doing maintenance that ended up requiring several restarts. The issue was confirmed and i was shortly reimbursed my materials, however if that wasn't possible this wouldve disheartened me for quite a bit, since I need to somehow get my hands on a vanilla beehive to get access to a renewable source of Nether Bannana's... :/

**Comment by SilentChaos512** [comment] 2022-02-23 23:28
Likely duplicate of #430. I'll take a look at this today, see if I can figure it out.

**Comment by SilentChaos512** [comment] 2022-02-24 20:26
Turned out to be a Silent Lib issue. It's fixed by Silent Lib 6.1.0.

**Comment by SilentChaos512** [comment] 2022-02-24 20:32
Hang on, need a couple small changes on this mod's side too...

**Closed as completed** 2022-02-24 20:40 UTC
Labels: bug
