### ISSUE TITLE
Stone Torch Lighting Bug

### ISSUE THREAD

**Issue by bryce-hoehn** [SilentChaos512/Silent-Gear#565] opened 2022-12-17 20:38 UTC
Hello, I'm using the stone torches from this mod in ATM8 and have been having this weird lighting bug: 
![image](https://user-images.githubusercontent.com/1351017/208265229-19c5764e-13c1-489a-91e5-8504c2a9d4cb.png)

It does not seem to affect vanilla torches or any other lighting sources that I've encountered so far.

**Comment by SilentChaos512** [comment] 2022-12-17 22:23
Duplicate of #537. I keep forgetting to fix that one...

**Closed as completed** 2022-12-18 03:04 UTC
