### ISSUE TITLE
Missing tool textures

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/Silent-Gear#190] opened 2020-07-25 22:26 UTC
## Versions

- **Silent's Gems**: v3.6.1+95
- **Silent Gear**: v1.10.2+136
- **Silent Lib**: v4.6.6+59
- **Forge**: v31.2.31
- **Modpack**: N/A 
- **Optifine Installed**: Yes
- **Datapack**: SGear Basic Metals v1.3

## Expected Behavior

- Items should not be missing textures

## Actual Behavior

- Several tools/weapons are missing textures.
- The sword I crafted is missing the crossguard.
- Several items in JEI are missing textures and say an invalid part is being used.
- Items currently missing textures: Sword Blade & Crossgaurd, Dagger Blade, Machete Blade, Stone Paxel Head, Lumber Axe, Mattock Head, Sickle Blade.

## Links/Images
![2020-07-25_17 14 15](https://user-images.githubusercontent.com/12000593/88467275-0eb1af80-ce9b-11ea-9e2f-afa3955b65af.png)
![2020-07-25_17 16 47](https://user-images.githubusercontent.com/12000593/88467343-baf39600-ce9b-11ea-8518-a9f55b0a5a4c.png)
![2020-07-25_17 20 38](https://user-images.githubusercontent.com/12000593/88467345-bd55f000-ce9b-11ea-8e8f-c2e70c7cb053.png)
![2020-07-25_17 20 49](https://user-images.githubusercontent.com/12000593/88467346-bf1fb380-ce9b-11ea-8812-22f030abdadc.png)

## Steps to Reproduce the Problem

1. Make a tool
2. Search in JEI

**Comment by Gbergz** [comment] 2020-11-12 16:22
There's still alot of textures missing on 1.16 aswell. Kind of annoying. Any news regarding this?

Edit: Mind you this isn't happening on a clean instance w/ Silent Gear only. Happens in a modpack, for instance in my modpack [TNP Limitless 3.](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3)

**Comment by SilentChaos512** [comment] 2020-11-12 16:48
@Gbergz Any idea what textures are missing or what causes it? Is it materials added by a data pack? I glanced through your pack's overrides, but I didn't see any materials.

**Comment by Gbergz** [comment] 2020-11-12 17:10
The following items have missing textures:
Compound Tool Rod
Compound Long Tool Rod
Compound Tip Upgrade
Compound Coating
Compound Grip
Compound Binding
Compound Bowstring
Compound Fletching

& any armor items, helmet, chestplate, leggings & boots.
![image](https://user-images.githubusercontent.com/26634554/98972143-5758ab80-2512-11eb-8a8f-d015a75bfd85.png)

**Comment by WiseHorror** [comment] 2020-11-14 16:36
I just tried changing resource packs (Vanilla Art), put it above LL3Resources and the textures aren't missing anymore (this is on TNP Limitless 3) however, when it's below LL3Resources the textures become missing again.

**Comment by Gbergz** [comment] 2020-11-14 17:54
> I just tried changing resource packs (Vanilla Art), put it above LL3Resources and the textures aren't missing anymore (this is on TNP Limitless 3) however, when it's below LL3Resources the textures become missing again.

Just tried this, and it seems to work. But also: just reloading the textures makes Silent Gears texture work again.
Restart the game and they're missing again.

**Comment by SilentChaos512** [comment] 2020-11-17 18:26
Could I get a client log from someone who is experiencing this please?

**Comment by WiseHorror** [comment] 2020-11-17 18:36
This is a few days old, but should do it https://hatebin.com/dlkvnsryvj

**Comment by SilentChaos512** [comment] 2020-11-17 22:30
I could not reproduce the broken textures, but I believe I have fixed the completely missing textures fixed in 2.3.7

**Comment by justtomisfine** [comment] 2020-11-22 07:04
Updated SG to 2.3.7 on All the Mods 6 and doesn't seem like the fix worked.

It also looks like upgrades cause an issue as well, for instance, the "spoon" upgrade causes pickaxes to get a missing texture.

**Comment by SilentChaos512** [comment] 2020-11-22 14:30
~Does anyone have a client log file showing missing texture errors?~ I guess the logs have no useful information.

**Comment by Hatsu-m** [comment] 2020-11-27 17:41
https://hatebin.com/hahkywrmah heres mine

**Comment by Hatsu-m** [comment] 2020-11-27 17:43
im also the one that reported the arrows not working but that might be all the mods 6 thing idk

**Comment by SilentChaos512** [comment] 2020-11-27 18:54
I was hoping for a log that specifically shows missing textures. Neither of the last two do.

**Comment by sine707** [comment] 2020-12-01 13:33
Here's my client log from ATM6. Should be noted that it only happens on every other bootup, sometimes it's missing, sometimes it's fine. This is from an instance where the textures are broken.

https://hatebin.com/wrigmusrtc

**Comment by SilentChaos512** [comment] 2020-12-01 13:51
Nothing useful in that one either. I'm looking for missing texture errors, something that looks like

`[19:50:09] [Worker-Main-14/ERROR] [minecraft/AtlasTexture]: Using missing texture, unable to load silentgear:textures/item/hammer/spoon.png : java.io.FileNotFoundException: silentgear:textures/item/hammer/spoon.png`

That one in particular occurs every time I launch in dev, due to a minor bug, but isn't a big issue since the spoon upgrade can't even be put on hammers.

**Comment by mkaito** [comment] 2020-12-02 12:54
ATM6 here too. I can reliably "fix" the missing textures by reloading resources with `F3+t`.

EDIT: Here's a log where textures were missing and they were fixed by reloading resources: https://paste.ee/p/2atJQ

**Comment by McKitten** [comment] 2021-01-05 07:45
Silly question time : Has anyone tried looking at the forge settings? It's not something I have played with on 1.15.2 but I've had to modify their options for earlier versions.

**Comment by mkaito** [comment] 2021-01-05 21:27
Things seem to work fine now.

**Closed as completed** 2021-02-22 03:16 UTC
Labels: bug, rendering
