### ISSUE TITLE
Server fails to start when updating from 2.8.8 to 2.9.0

### ISSUE THREAD

**Issue by evhub** [SilentChaos512/Silent-Gear#494] opened 2022-02-25 07:42 UTC
When updating from Silent Gear 2.8.8 to 2.9.0, the new version causes the server to crash immediately during startup.

## Versions

- **Silent Gear**: 2.9.0
- **Silent's Gems**: N/A
- **Silent Lib**: 6.1.0
- **Forge**: 39.0.85
- **Modpack**: N/A
- **Optifine Installed**: No

## Links/Images

Logs: https://gist.github.com/evhub/68cc2f0a0acb2c826405e41290270ccd

(no crash report is generated as the crash happens too early in server startup)

**Comment by krjencik** [comment] 2022-02-25 09:52
same with forge 39.0.88
removed configs still a crash

when using silent lib 6.1.0 and silent gear 2.8.8 it works

**Comment by Zedrimar** [comment] 2022-02-26 22:46
I found this line in debug.log, may help in figuring out the crash (happens even when using java 17.0.2)

silentgear.mixins.json:MixinItemEntity: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_16 supports class version 60)

https://pastebin.com/7gjxhgvL

**Comment by Kowantify** [comment] 2022-02-27 16:27
Same Issue for me

Silent lib 6.1.0 Works
Silent gear 2.8.8 Works, V2.9.0 crashes

**Comment by SilentChaos512** [comment] 2022-03-02 12:43
> I found this line in debug.log, may help in figuring out the crash (happens even when using java 17.0.2)
> 
> silentgear.mixins.json:MixinItemEntity: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_16 supports class version 60)
> 
> https://pastebin.com/7gjxhgvL

Doesn't seem to be the cause of the crash unfortunately...

I actually get a crash report in dev. It's a complete head-scratcher though. Seems like something is loading the `LocalPlayer` class, but I have no idea how.

https://gist.github.com/SilentChaos512/6fd29a905ad398d1f7508b9c54633321

**Comment by ScoutTheSaneless** [comment] 2022-03-02 19:56
can confirm on my end as well

**Comment by McSquizzleswag** [comment] 2022-03-06 17:07
This crash also happens on client side

**Comment by SilentChaos512** [comment] 2022-03-09 02:51
@McSquizzleswag Can you provide a crash report or log file from your client? Are you sure it's the same issue?

**Comment by McSquizzleswag** [comment] 2022-03-09 22:59
I am running the two mods stated in the original issue as part of a pack and am getting the crash, it also happens with your other two mods present
https://gist.github.com/McSquizzleswag/f4bfa98a3ac87e66bbb2fd2c930aadeb

**Comment by McSquizzleswag** [comment] 2022-03-09 23:16
Ran the two mods on their own, both are the beta versions
https://gist.github.com/McSquizzleswag/12be90b27764a0525671668389b21ec8

**Comment by SilentChaos512** [comment] 2022-03-10 10:44
Yeah, that's the same `No refMap loaded` error for the `ItemEntity` mixin. How odd. I tried updating to Forge 39.1.2 in my dev environment, but the client still loads up just fine. Server still crashes with an unrelated error in dev.

**Comment by McSquizzleswag** [comment] 2022-03-10 13:18
I had brought this up in the Forge discord (unfortunately the messages involving this were deleted for some reason) it was suggested that `@onlyin` could be a factor

**Comment by SilentChaos512** [comment] 2022-03-11 02:25
I found a workaround for the in dev crash... But there's still no crash like the one described here.

**Comment by SilentChaos512** [comment] 2022-03-15 21:18
Should be fixed in version 2.9.1... Seems like 2.9.0 was just a bad build. No code changes were made.

Can anyone else confirm the issue is fixed?

**Comment by EntropicPariah** [comment] 2022-03-16 01:06
> Should be fixed in version 2.9.1... Seems like 2.9.0 was just a bad build. No code changes were made.
> 
> Can anyone else confirm the issue is fixed?

Seems fixed for me. Loaded up with no problems at all

**Comment by SilentChaos512** [comment] 2022-03-16 10:49
Thanks, I'll close this issue now.

**Closed as completed by SilentChaos512** 2022-03-16 10:49 UTC
Labels: bug
